import { Roboto } from "next/font/google";

import { Toaster } from "@pheralb/toast";
import ReduxProvider from "@/providers/ReduxProvider";
import TanstackqueryProvider from "@/providers/TanstackqueryProvider";

import type { Metadata } from "next";

import "./globals.css";

const roboto = Roboto({
    subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            lang="en"
            className="mdl-js"
        >
            <body
                className={`${roboto.className} text-zinc-800 antialiased`}
            >
                <TanstackqueryProvider>
                    <ReduxProvider>
                        {children}
                    </ReduxProvider>
                </TanstackqueryProvider>

                <Toaster position="top-right" />
            </body>
        </html>
    );
}