import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import ReduxProvider from "@/providers/ReduxProvider";

import "./globals.css";

const roboto = Roboto({
    subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className="mdl-js"
        >
            <body
                className={`${roboto.className} text-zinc-800 antialiased`}
            >
                <ReduxProvider>
                    {children}
                </ReduxProvider>
            </body>
        </html>
    );
}